blog/urls.py
from django.urls import path
from . import views
from .feeds import LatestPostFeed

app_name = 'blog'

urlpatterns = [
    path('', views.post_list, name='post_list'),

    path('tag/<slug:tag_slug>/',views.post_list,name='post_list_by_tag'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/',
            views.post_detail,name='post_detail'),
    path('<int:post_id>/share/',views.post_share,name='post_share'),
    path('feed/', LatestPostFeed(), name='post_feed'),
    path('search/', views.post_search, name='post_search')

]

mysite/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap

sitemaps = {
    'posts':PostSitemap,
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls',namespace='blog')),
    path('sitemap.xml', sitemap, {'sitemaps':sitemaps},
         name='django.contrib.sitemaps.views.sitemap')
]

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User 
from django.urls import reverse

from taggit.managers import TaggableManager
# Create your models here.


class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager,
                    self).get_queryset()\
                        .filter(status='published')

class Post(models.Model):
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published','Published'),
    )
    title    = models.CharField(max_length = 200)
    slug     = models.SlugField(max_length= 200,
                                unique_for_date='publish')
    author   = models.ForeignKey(User,
                                 on_delete=models.CASCADE,
                                 related_name='blog_posts')
    body     = models.TextField()
    publish  = models.DateField( default =timezone.now)
    # timezone.now method returns current datetime
    created  = models.DateField( auto_now_add=True)
    # auto_now_add will be saved automatically when
    # creating an object
    updated  = models.DateField( auto_now=True)
    # auto_now will be updated automatically when\
    #  saving an obj(showing last updated time)
    status   = models.CharField( max_length=10,
                                choices=STATUS_CHOICES,
                                default='darft')
    # This field shows the status of a psot.You use a chices parameter \
    # so the value of this field can only be set to one of the given choices.
    objects  = models.Manager() # the default manager.
    published= PublishedManager() # Our custom manager.

    tags = TaggableManager()


    class Meta:
        ordering = ('-publish',)

    def get_absolute_url(self):
        return reverse('blog:post_detail', args=[self.publish.year,
                                                self.publish.month,
                                                self.publish.day,
                                                self.slug])
    

    def __str__(self):
        return self.title         


class Comment(models.Model):
    post = models.ForeignKey(Post,
                            on_delete=models.CASCADE,
                            related_name='comments')
 

    """The Relative_name attribute allows you to name the attribute that you use
    for the relationship from the related object back to this one. You can retrieve
    the post of a comment object using comment.post and retrieve all comments of a post
    using post.commets.all()  . If YOu don't define related_name attribute. 
    Django will use the name of the model in lowercase follwed by _set (that is, comment_set)
    to name the relationship of the related object of the model, where this relationship 
    has been defined."""

    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)


    class Meta:
        ordering = ['created']

    def __str__(self):
        return f'Comment by {self.name} on {self.post}'
                                                                                                                                                                                                                                                                                                                                   
    

blog/forms.py
from django import forms 
from .models import Comment

class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=30)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False,widget=forms.Textarea)

# class CommentForm(forms.Form):
#     name = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control'}))
#     email = forms.EmailField(widget=forms.EmailInput(attrs={'class':'form-control'}))
#     body = forms.CharField(widget=forms.Textarea(attrs={'class':'form-control'}))
    


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name','email', 'body')

        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
            'body':forms.Textarea(attrs={'class':'form-control'})
        }

class SearchForm(forms.Form):
    query = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control'}))

blog/views.py
from django.db.models import Count
from django.shortcuts import render,get_object_or_404
from django.core.paginator import Paginator,EmptyPage,\
    PageNotAnInteger
from taggit.models import Tag



from .models import Post, Comment
from .forms import EmailPostForm, CommentForm, SearchForm
from django.contrib.postgres.search import (
    SearchVector,SearchQuery,SearchRank,
    TrigramSimilarity
)
from django.core.mail import send_mail
# Create your views here.

def post_list(request, tag_slug=None):
    object_list = Post.published.all()
    tag = None
    tags = Post.tags.all
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        object_list = object_list.filter(tags__in=[tag])
    paginator   = Paginator(object_list, 3)
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
    return render(request,
    'blog/post/list.html',
    {'page':page,
    'posts': posts,
    'tag':tag,  
    'tags':tags})

def post_detail(request, year,month,day,post):
    post = get_object_or_404(Post,slug=post,
                                status='published',
                                publish__year=year,
                                publish__month=month,
                                publish__day=day)
    post_tags_ids = post.tags.values_list('id', flat=True)
    similar_posts = Post.published.filter(tags__in=post_tags_ids).exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count('tags')).order_by('-same_tags','-publish')[:4]

     # List of active comments for this particular post 
    comments = post.comments.filter(active=True)
    tags = post.tags.all()
    new_comment = None
    if request.method == 'POST':
        # A Comment was Posted
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            # Create Comment Object (instance) but don't save to database yet
            # this comes in handy when you want to modify the object before finally saving it,
            # which is what you will do next.
            new_comment = comment_form.save(commit=False)
            # Assign the current post to the comment
            new_comment.post = post
            # Save the comment to the database
            new_comment.save()
    else:
        comment_form = CommentForm()

    return render(request, 'blog/post/detail.html',
                            {'post':post,
                            'similar_posts': similar_posts,
                            'tags':tags,
                            'comments':comments,
                            'new_comment':new_comment,
                            'comment_form':comment_form})                           

def post_share(request,post_id):
    # Retrieve post by id
    post = get_object_or_404(Post, id=post_id, status='published')
    sent = False

    if request.method == 'POST':
        # Form was submitted
        form = EmailPostForm(request.POST)
        if form.is_valid():
            # Form fields passed validation
            cd = form.cleaned_data

            # ... send email
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = f" {cd['name']} recommends you read " \
                        f" {post.title} "
            message = f" Read {post.title} at {post_url}\n\n" \
                        f"{cd['name']}\'s comments: {cd['comments']} "
            send_mail(subject, message, 'mainulislamfaruqi@gmail.com',[cd['to']])
            sent = True
    else:
        form = EmailPostForm()
    return render(request, 'blog/post/share.html',{'post':post,
                                                'form':form,
                                                'sent':sent})

            


def post_search(request):
    form = SearchForm()
    query = None
    results = []
    if 'query' in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']

            search_vector = SearchVector('title', weight='A') +\
                            SearchVector('body', weight='B')
            search_query = SearchQuery(query)
            results = Post.published.annotate(
                similarity =TrigramSimilarity('title',query),
            ).filter(similarity__gt=0.1).order_by('-similarity')
            # results = Post.published.annotate(
            #     search=SearchVector('title','body'),
            #     ).filter(search=query)


    return render(request,'blog/post/search.html',
                  {'form':form,
                  'query':query,
                  'results':results})

blog/templates/blog/base.html
{% load blog_tags %}
{% load static %}
<!DOCTYPE html>
<html>
<head>
  <title>{% block title %}{% endblock %}</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
  
  <link href="{% static 'css/blog.css' %}" rel="stylesheet">
</head>
<body>

  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#" style="color: #00abff;">Crazy Python Lover </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mx-auto">
        <li class="nav-item ">
          <a class="nav-link" href=" {% url 'blog:post_list' %} ">Home <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item {% block active %} {% endblock %} ">
          <a class="nav-link" href=" {% url 'blog:post_list' %}"> Blog </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#"> About us </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#"> Contact us </a>
        </li>
      </ul>
      <form method="GET" action=" {% url 'blog:post_search' %} " class="form-inline my-2 my-lg-0">
        <input class="form-control mr-sm-2 my-2" type="search" placeholder="Search" aria-label="Search" name="query" id="query">
        <button id="my-button" class="btn  btn-outline my-button my-2 my-sm-0" type="submit" value="Search">Search</button>
      </form>
    </div>
  </nav>

<div class="container"> 


  <div id="content">
    {% block content %}
    {% endblock %}
  </div>
  <div id="sidebar">
    <h2>My blog</h2>
    <p>This is my blog. I've written {% total_posts %} posts so far.</p>
    <p><a href="{% url "blog:post_feed" %}">Subscribe to my RSS feed</a></p>
    <h3>Latest posts</h3>
    {% show_latest_posts 9 %}
    <h3>Most commented posts</h3>
    {% get_most_commented_posts as most_commented_posts %}
    <ul>
      {% for post in most_commented_posts %}
        <li>
          <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
        </li>
      {% endfor %}
    </ul>
  </div>

</div>
 
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
</body>
</html>